#!/bin/bash

#umask 002
#cd ~/home/buchholz/code_database/code_sets/firex

#---------------------------------------

# link the updated colormap
#setenv NCARG_COLORMAPS /glade/home/buchholz/code_database/code_sets/firex/colormaps:$NCARG_ROOT/lib/ncarg/colormaps

#---------------------------------------
  run_folder=/IASI/home/buchholz/code_database/code_sets/firex

# determine dates of run
# Shawn's WACCM forecast
  folder_base=/waccm-output/
# Set date
#  set current_date = `date +%Y-%m-%d` 
#  set forecast_date = `date +%Y%m%d`
# Set folder
  folder=${folder_base}
  #files=f.e21.FWSD.f09_f09_mg17.forecast.001.cam.h3.
  files=f.e22.beta02.FWSD.f09_f09_mg17.cesm2_2_beta02.forecast.001.cam.h3.

  file_list="$(ls ${folder}${files}*2019-08-07*)"


echo $file_list
for x in $file_list ; do
    echo ${x} \

    dummy=$(echo "$x" | sed 's/\/waccm-output\/f.e22.beta02.FWSD.f09_f09_mg17.cesm2_2_beta02.forecast.001.cam.h3.//g')   # remove year specific to file

    forecast_date_dummy=$(echo "$dummy" | sed 's/-00000.nc//g')
    #forecast_date=2018-09-01

    forecast_date=$(echo "$forecast_date_dummy" | sed 's/-//g')
    echo ${forecast_date} \

    forecast_date=20190806

    #echo ${forecast_date} 

#---------------------------------------
# run the plot routines on each file

   #ncl filename=\"$x\" file_prefix=\"$folder$files\" STATION=True forecast_date=$forecast_date $run_folder/firex_wrapper.ncl
   #ncl filename=\"$x\" CURTAIN=True forecast_date=$forecast_date $run_folder/firex_wrapper.ncl
   ncl filename=\"$x\" LATLON=True forecast_date=$forecast_date $run_folder/firex_wrapper.ncl
   ncl filename=\"$x\" LATLON_WUS=True forecast_date=$forecast_date $run_folder/firex_wrapper.ncl
   ncl filename=\"$x\" LATLON_SEUS=True forecast_date=$forecast_date $run_folder/firex_wrapper.ncl

#---------------------------------------

done
