#!/bin/tcsh
#
#PBS -N waccm_plot           ### job name
#PBS -j oe                   ### combine error and output files
#PBS -A P19010000            ### project code
#PBS -l walltime=02:00:00    ### wall-clock time (hrs:mins:secs)
#PBS -q regular              ### queue
### Request one chunk with ncpus and mpiprocs set to
### the number of lines in the command file
#PBS -l select=1:ncpus=21:mpiprocs=21  ###select nodes
#PBS -m e                    ### email when done
#PBS -M buchholz@ucar.edu    ### email address

umask 002
cd /glade/u/home/buchholz/code_database/code_sets/waccm_forecasts

#---------------------------------------
# load NCL
source /glade/u/apps/opt/lmod/4.2.1/init/tcsh
module load ncl
module list

# link the updated colormap
setenv NCARG_COLORMAPS /glade/home/buchholz/code_database/code_sets/waccm_forecasts/colormaps:$NCARG_ROOT/lib/ncarg/colormaps

#---------------------------------------
  set run_folder = "/glade/u/home/buchholz/code_database/code_sets/waccm_forecasts"

#  Hardcode date
#  set current_date = "2019-08-01"
#  set forecast_date = 20190801

# determine dates of run
# Jerome's forecast
#  set folder = "/glade/scratch/barre/archive/KORUS_forecast_3inst/atm/hist/"
#  set files = "KORUS_forecast_3inst.cam_0001.h1."

# Shawn's WACCM forecast
  set folder_base = "/glade/scratch/shawnh/GEOS5_frcst_data/"
# Set date
  set current_date = `date +%Y-%m-%d`
  set forecast_date = `date +%Y%m%d`
# Set folder
  set folder = ${folder_base}/${forecast_date}/model_files.0/finn/
  set files = "f.e21.FWSD.f09_f09_mg17.forecast.001.cam.h3."




#---------------------------------------
# set up a command file
set j = 0
# while ( $j <= 0 )
 while ( $j <= 5 )
   echo "Submitting: `date --date='$current_date +$j day' +%Y-%m-%d`"
   set date_run = `date --date="$current_date +$j day" +%Y-%m-%d`

   if ($j == 0) then
     echo ncl \'filename=\"$folder$files$date_run-00000.nc\"\' \'file_prefix=\"$folder$files\"\' STATION=True forecast_date=$forecast_date $run_folder/firex_wrapper.ncl >> /glade/u/home/buchholz/code_database/code_sets/firex/cmd_file.txt
     echo ncl \'filename=\"$folder$files$date_run-00000.nc\"\' CURTAIN=True forecast_date=$forecast_date $run_folder/firex_wrapper.ncl >> /glade/u/home/buchholz/code_database/code_sets/firex/cmd_file.txt
     echo ncl \'filename=\"$folder$files$date_run-00000.nc\"\' LATLON=True forecast_date=$forecast_date $run_folder/firex_wrapper.ncl >> /glade/u/home/buchholz/code_database/code_sets/firex/cmd_file.txt
     echo ncl \'filename=\"$folder$files$date_run-00000.nc\"\' LATLON_WUS=True forecast_date=$forecast_date $run_folder/firex_wrapper.ncl >> /glade/u/home/buchholz/code_database/code_sets/firex/cmd_file.txt
     echo ncl \'filename=\"$folder$files$date_run-00000.nc\"\' LATLON_SEUS=True forecast_date=$forecast_date $run_folder/firex_wrapper.ncl >> /glade/u/home/buchholz/code_database/code_sets/firex/cmd_file.txt
   else
     echo ncl \'filename=\"$folder$files$date_run-00000.nc\"\' CURTAIN=True forecast_date=$forecast_date $run_folder/firex_wrapper.ncl >> /glade/u/home/buchholz/code_database/code_sets/firex/cmd_file.txt
     echo ncl \'filename=\"$folder$files$date_run-00000.nc\"\' LATLON=True forecast_date=$forecast_date $run_folder/firex_wrapper.ncl >> /glade/u/home/buchholz/code_database/code_sets/firex/cmd_file.txt
     echo ncl \'filename=\"$folder$files$date_run-00000.nc\"\' LATLON_WUS=True forecast_date=$forecast_date $run_folder/firex_wrapper.ncl >> /glade/u/home/buchholz/code_database/code_sets/firex/cmd_file.txt
     echo ncl \'filename=\"$folder$files$date_run-00000.nc\"\' LATLON_SEUS=True forecast_date=$forecast_date $run_folder/firex_wrapper.ncl >> /glade/u/home/buchholz/code_database/code_sets/firex/cmd_file.txt
   endif

   @ j++
 end

#---------------------------------------
# load parallel
setenv MP_PGMMODEL mpmd
# run the NCL plotting in parallel
mpirun.lsf -cmdfile /glade/u/home/buchholz/code_database/code_sets/firex/cmd_file.txt

#---------------------------------------
# clean up
# delete command file
rm -f /glade/u/home/buchholz/code_database/code_sets/firex/cmd_file.txt

  echo "Successfully plotted all tracers"
  echo "END OF PLOT ROUTINES"


#---------------------------------------
